### ISSUE TITLE
Vinted API not accessable anymore?

### ISSUE THREAD

**Issue by mpeterit** [herissondev/vinted-api-wrapper#22]
Since yesterday, 19th of November 2024, I am having trouble reaching the Vinted API. Very similiar to your source code I am sending following requests:
- POST-Request to: https://www.vinted.fr/auth/token_refresh
- GET-Request to: https://www.vinted.fr/api/v2/catalog/items

Usually this would lead me to have access to the api endpoint. Since yesterday this is not the case anymore and i get a response 401 Unauthorized: 
```
{
    "code": 100,
    "message": "Jeton d'authentification invalide",
    "message_code": "invalid_authentication_token"
}
```
Do you encounter the same issues? If yes can we confirm that the vinted API was closed to public? If not can we find a way to solve this problem? I am open to contribute in the problem solving process, if there is a way.

**Comment by herissondev** [comment]
It has being reported but did not have time to look into it yet. They probably changed the way auth token are fetched

**Comment by Dodouce** [comment]
I'm also interested on any news about this.
I am using this repo very often and I'm facing the same issue.

P.S : thanks for the great job done here !

**Comment by herissondev** [comment]
Hello everyone, the issue has being identified, i'm just missing time to make the update. Basically auth requests should not send a post request to /token_refresh but a simple **HEAD** request to the main page ("https://www.vinted.fr"). This should set the cookies correctly

**Comment by Fuyucch1** [comment]
That's the workaround I've been using for the past few days and I've encountered no issues since. Looks like the proper solution 👍

**Comment by herissondev** [comment]
The issue is now fixed please update to version 0.5.2 of pyVinted

**Comment by ik1llo** [comment]
Hi, i always get 
{
  code: 21,
  message: 'Nombre de usuario requerido',
  message_code: 'user_login_required',
  payload: {}
}

when i send my requests like:

           const response = await fetch(
                process.env.RESELL_VINTED_BASE_URL, 
                {
                    ...get_default_request_options(),
                    method: "HEAD"
                }
            );
my get_default_request_options is:

export const get_default_request_options = () => {
    return {
        agent: proxy_agent,
        credentials: "include",
        headers: {
            "Content-Type": "application/json",
            "User-Agent": "xxx",
            "Authorization": `Bearer ${ tokens_refresher.access_token }`,
            "x-csrf-token": "xxx"
        },
        mode: "cors"
    }
}

i get my set-cookie header with a new access_token_web cookie, but when i'm trying to make a request with this access_token, it returns me what i've showed above

**Comment by ik1llo** [comment]
Update: the token is valid and functional, but Vinted requires me to log in. What request should I make? I'm using Google for OAuth2
